version: '3.8'

volumes:
  n8n_storage:

x-shared: &shared
  restart: always
  build: .
  environment:
    # 数据库
    - DB_TYPE=postgresdb
    - DB_POSTGRESDB_HOST=${POSTGRES_HOST:-postgres}
    - DB_POSTGRESDB_PORT=${POSTGRES_PORT:-5432}
    - DB_POSTGRESDB_DATABASE=${POSTGRES_DB:-n8n}
    - DB_POSTGRESDB_USER=${POSTGRES_USER}
    - DB_POSTGRESDB_PASSWORD=${POSTGRES_PASSWORD}

    # 队列模式和 redis
    - EXECUTIONS_MODE=queue
    - QUEUE_BULL_REDIS_DB=${REDIS_DB:-8}
    - QUEUE_BULL_REDIS_HOST=${REDIS_HOST:-redis}
    - QUEUE_BULL_REDIS_PORT=${REDIS_PORT:-6379}
    - QUEUE_BULL_REDIS_PASSWORD=${REDIS_PASSWORD}
    - QUEUE_HEALTH_CHECK_ACTIVE=true

    # 回调地址设置
    - WEBHOOK_URL=${WEBHOOK_URL}

    # 关闭统计 https://docs.n8n.io/hosting/environment-variables/configuration-examples/isolation/
    - N8N_DIAGNOSTICS_ENABLED=false
    - N8N_VERSION_NOTIFICATIONS_ENABLED=false
    - N8N_TEMPLATES_ENABLED=false
    - EXTERNAL_FRONTEND_HOOKS_URLS=
    - N8N_DIAGNOSTICS_CONFIG_FRONTEND=
    - N8N_DIAGNOSTICS_CONFIG_BACKEND=

    # 关闭广告
    - N8N_HIRING_BANNER_ENABLED=false

    # 时区
    - GENERIC_TIMEZONE=Asia/Hong_Kong

    # 允许代码块使用任何内置库
    - NODE_FUNCTION_ALLOW_BUILTIN=*

    # 允许代码块使用外置库列表
    - NODE_FUNCTION_ALLOW_EXTERNAL=file-type

    # 高级功能
    - N8N_FEAT_ADVANCEDEXECUTIONFILTERS_ENABLE=1
    - N8N_FEAT_APIDISABLED_ENABLE=1
    - N8N_FEAT_BINARYDATAS3_ENABLE=1
    - N8N_FEAT_DEBUGINEDITOR_ENABLE=1
    - N8N_FEAT_EXTERNALSECRETS_ENABLE=1
    - N8N_FEAT_LDAP_ENABLE=1
    - N8N_FEAT_LOGSTREAMING_ENABLE=1
    - N8N_FEAT_MULTIPLEMAININSTANCES_ENABLE=1
    - N8N_FEAT_SAML_ENABLE=1
    - N8N_FEAT_SHARING_ENABLE=1
    - N8N_FEAT_SOURCECONTROL_ENABLE=1
    - N8N_FEAT_VARIABLES_ENABLE=1
    - N8N_FEAT_WORKERVIEW_ENABLE=1
    - N8N_FEAT_WORKFLOWHISTORY_ENABLE=1
  volumes:
    - n8n_storage:/home/node/.n8n
    - /var/run/docker.sock:/var/run/docker.sock
  networks:
    - 1panel-network

services:
  n8n:
    <<: *shared
    ports:
      - 5678:5678

  n8n-worker:
    <<: *shared
    command: worker
    depends_on:
      - n8n

networks:
  1panel-network:
    external: true
