version: '3.8'

volumes:
  n8n_storage:

x-shared: &shared
  restart: always
  build: .
  environment:
    - DB_TYPE=postgresdb
    - DB_POSTGRESDB_HOST=${POSTGRES_HOST:-postgres}
    - DB_POSTGRESDB_PORT=${POSTGRES_PORT:-5432}
    - DB_POSTGRESDB_DATABASE=${POSTGRES_DB:-n8n}
    - DB_POSTGRESDB_USER=${POSTGRES_USER}
    - DB_POSTGRESDB_PASSWORD=${POSTGRES_PASSWORD}
    - EXECUTIONS_MODE=queue
    - QUEUE_BULL_REDIS_DB=${REDIS_DB:-8}
    - QUEUE_BULL_REDIS_HOST=${REDIS_HOST:-redis}
    - QUEUE_BULL_REDIS_PORT=${REDIS_PORT:-6379}
    - QUEUE_BULL_REDIS_PASSWORD=${REDIS_PASSWORD}
    - QUEUE_HEALTH_CHECK_ACTIVE=true
    - WEBHOOK_URL=${WEBHOOK_URL}
    - N8N_FEAT_ADVANCEDEXECUTIONFILTERS_ENABLE=1
    - N8N_FEAT_APIDISABLED_ENABLE=1
    - N8N_FEAT_BINARYDATAS3_ENABLE=1
    - N8N_FEAT_DEBUGINEDITOR_ENABLE=1
    - N8N_FEAT_EXTERNALSECRETS_ENABLE=1
    - N8N_FEAT_LDAP_ENABLE=1
    - N8N_FEAT_LOGSTREAMING_ENABLE=1
    - N8N_FEAT_MULTIPLEMAININSTANCES_ENABLE=1
    - N8N_FEAT_SAML_ENABLE=1
    - N8N_FEAT_SHARING_ENABLE=1
    - N8N_FEAT_SHOWNONPRODBANNER_ENABLE=1
    - N8N_FEAT_SOURCECONTROL_ENABLE=1
    - N8N_FEAT_VARIABLES_ENABLE=1
    - N8N_FEAT_WORKERVIEW_ENABLE=1
    - N8N_FEAT_WORKFLOWHISTORY_ENABLE=1
  volumes:
    - n8n_storage:/home/node/.n8n
    - /var/run/docker.sock:/var/run/docker.sock
  networks:
    - 1panel-network

services:
  n8n:
    <<: *shared
    ports:
      - 5678:5678

  n8n-worker:
    <<: *shared
    command: worker
    depends_on:
      - n8n

networks:
  1panel-network:
    external: true
